### PR TITLE
Adding useNpmCache parameter

### PR DESCRIPTION
**Pull request by jpjcjbr**
I had an issue having to call npm instead of npm-cache in some cases, so I added the useNpmCache parameter to enable npm-cache when it is needed.

It is also related to issue #30 created by @briancmills

Thanks

### CODE REVIEW

**Comment by trecloux** [comment]
Thanks @jpjcjbr , can you please edit your changes and cancel the changelog entry ?

Thanks

**Comment by jpjcjbr** [comment]
Sure @trecloux, done!

Let me know if any other change is needed

**Comment by trecloux** [comment]
@jpjcjbr It would be perfect if you could rebase your branch for an easier merge.

**Comment by jpjcjbr** [comment]
@trecloux, I'm not sure if I did it the right way, could you please check it again?

**Pull request closed without merging**
